Added support for email_verified being a string or bool
sigstore/fulcio pull request #1744
Opened 2024-07-28 20:50 UTC by sabre1041

#### Summary

Introduces support for `email_verifed` claim to be either a boolean or string value

References https://github.com/sigstore/sigstore/issues/1698

#### Release Note

* Boolean and String data type support for `email_verified` claim

2024-07-29 01:09 UTC, haydentherapper requested changes
https://github.com/sigstore/sigstore/issues/1698#issuecomment-2052628831 mentions that this would not be spec-compliant. Has there been any attempt to resolve this via the IDP?

2024-07-29 19:29 UTC, sabre1041 commented
> [sigstore/sigstore#1698 (comment)](https://github.com/sigstore/sigstore/issues/1698#issuecomment-2052628831) mentions that this would not be spec-compliant. Has there been any attempt to resolve this via the IDP?

This is a limitation (only one of many) of Azure as also mentioned in the referenced issue.

However, there is already some precedence in the library sigstore uses to workaround this same limitation

https://github.com/coreos/go-oidc/blob/v3/oidc/oidc.go#L309
https://github.com/coreos/go-oidc/blob/v3/oidc/oidc.go#L491-L503

2024-07-30 20:19 UTC, haydentherapper approved these changes
Thanks, will get a new release cut after the open PRs get merged.

2024-07-30 20:20 UTC, merged

2024-07-30 20:25 UTC, sabre1041 commented
@haydentherapper thanks a bunch!

Theres a similar change incoming for https://github.com/sigstore/sigstore that will be submitted soon