feat: adds cert templates.
sigstore/fulcio pull request #1870
Opened 2024-11-21 20:20 UTC by ianhundere

closes #1869 

#### Summary

#### Release Note

#### Documentation

2024-11-25 20:18 UTC, ianhundere commented
i think this is ready for some 👀 

cc @haydentherapper

2024-11-26 15:26 UTC, ianhundere commented
err, i should probably tweak this a bit to specify the current intermediate template as leaf and provide the capability to create intermediate certs (isCA).

```
Root CA -> Intermediate CA -> Leaf Certificate
```

any reason we should increase the number of intermediate certs to more than 1 like so? 
```
Root CA -> Intermediate CA 1 -> Intermediate CA 2 -> Leaf Certificate
```

2024-12-01 00:33 UTC, ianhundere commented
i think this is ready for 👀 now. just a couple of notes.

1. the following use-cases are now covered:
  - `root ca -> leaf`
  - `root ca -> intermediate ca -> leaf`

2. both `awskms` and `azurekms` have been tested / work, but `cloudkms` (e.g. gcp), has not been tested.

i think that about covers, i have some basic readmes above as well.

2024-12-01 06:41 UTC, ianhundere commented
i think this is ready for 👀 now. just a couple of notes.

1. the following use-cases are now covered:
  - `root ca -> leaf`
  - `root ca -> intermediate ca -> leaf`

2. both `awskms` and `azurekms` have been tested / work, but `cloudkms` (e.g. gcp), has not been tested.

i think that about covers it, i have some basic readme/documentation above as well.

cc @haydentherapper

2024-12-04 04:03 UTC, haydentherapper commented
Thanks @ianhundere, I’ll take a look at this later this week.

2024-12-09 16:00 UTC, ianhundere commented
> Thanks @ianhundere, I’ll take a look at this later this week.

@haydentherapper resolved some lint errors / should be ready for 👀 now.

2024-12-12 14:59 UTC, ianhundere commented
a nudge for 👀 

cc @haydentherapper / @bobcallaway

2024-12-12 15:11 UTC, bobcallaway commented on cmd/certificate_maker/certificate_maker.go
> +	createCmd.Flags().StringVar(&kmsType, "kms-type", "", "KMS provider type (awskms, cloudkms, azurekms)")
can we say `gcpkms` to be consistent with the naming schemes used elsewhere in fulcio and sigstore?

2024-12-12 15:12 UTC, bobcallaway commented on cmd/certificate_maker/certificate_maker.go
> +	createCmd.Flags().StringVar(&kmsTenantID, "kms-tenant-id", "", "Azure KMS tenant ID")
perhaps add `azure` into the flag name to denote it's only applicable for that provider?

2024-12-12 17:20 UTC, ianhundere commented on pkg/certmaker/certmaker.go
> +	"go.step.sm/crypto/kms/cloudkms"
ah yes / https://github.com/smallstep/crypto is more focused on certificate generation which is why i went that route (e.g. feeding it cert templates etc).

2024-12-13 20:21 UTC, ianhundere commented
@haydentherapper / @haydentherapper 

just a heads up that i tested `gcpkms` and it's working:
```shell
❯ ./fulcio-certificate-maker create --kms-type gcpkms --gcp-credentials-file ~/.config/gcloud/application_default_credentials.json --root-key-id projects/blah/locations/global/keyRings/sigstore/cryptoKeys/fulcio-root/cryptoKeyVersions/1 --leaf-key-id projects/blah/locations/global/keyRings/sigstore/cryptoKeys/fulcio-leaf/cryptoKeyVersions/1 --root-cert root.pem --leaf-cert leaf.pem
Your root certificate has been saved in root.pem.
Your leaf certificate has been saved in leaf.pem.
```

2024-12-16 17:13 UTC, ianhundere commented
i also removed `testify` / updated tests to avoid pulling in further dependencies

2024-12-19 06:26 UTC, ianhundere commented on pkg/certmaker/certmaker.go
> +	"go.step.sm/crypto/kms/cloudkms"
i replaced it w/ sigstore/sigstore.

2024-12-19 06:26 UTC, ianhundere commented
this is ready for another 👀 

cc @haydentherapper / @bobcallaway

2025-01-06 13:24 UTC, ianhundere commented
another nudge for 👀 / thanks y'all

cc @haydentherapper / @bobcallaway

2025-01-15 15:29 UTC, ianhundere commented
ah, thought this was me, but looks like another test:
- https://github.com/sigstore/fulcio/actions/runs/12769072721/job/35656859546?pr=1870#step:7:1371

2025-01-16 22:21 UTC, bobcallaway commented on .gitignore
> +.DS_Store
should you also add the binary name `fulcio-certificate-maker` here so it doesn't get checked in by accident?

2025-01-16 22:21 UTC, bobcallaway commented on cmd/certificate_maker/certificate_maker.go
> +	rawJSON = []byte(`{
I'd define this locally within the method it is used as a native struct; I don't see the benefit of unmarshalling it from JSON

2025-01-16 22:21 UTC, bobcallaway commented on cmd/certificate_maker/certificate_maker.go
> +func getConfigValue(flagValue, envVar string) string {
as an aside, i've used https://github.com/spf13/viper?tab=readme-ov-file#working-with-flags to bind flags and env vars so that you can just call `viper.GetString()` on a flag and it reconciles the sources in a consistent order.

we're already using this as a dependency within fulcio so perhaps it is less footprint to reuse that?

2025-01-17 17:01 UTC, ianhundere commented on .gitignore
> +.DS_Store
good point / thanks.

2025-01-17 17:01 UTC, ianhundere commented on cmd/certificate_maker/certificate_maker.go
> +	rawJSON = []byte(`{
ah, thanks for catching that.

2025-01-17 17:02 UTC, ianhundere commented on cmd/certificate_maker/certificate_maker.go
> +func getConfigValue(flagValue, envVar string) string {
oh nice, that's a lot cleaner / thanks.

2025-01-17 17:05 UTC, ianhundere commented
@bobcallaway thanks again for the feedback / i also transitioned to just using `fulcio/pkg/log"` for logging as well as cleaned up the erroring depending on if it's for usage errors, show help, or operational errors, show json error.

2025-01-21 22:52 UTC, haydentherapper requested changes

2025-01-21 22:52 UTC, haydentherapper commented on cmd/certificate_maker/certificate_maker.go
> +	mustBindPFlag("kms-type", createCmd.Flags().Lookup("kms-type"))
Do you need both flag binding and initializing global variables?

2025-01-21 22:52 UTC, haydentherapper commented on cmd/certificate_maker/certificate_maker.go
> +	createCmd.Flags().StringVar(&kmsRegion, "aws-region", "", "AWS KMS region")
If this is specific to aws only, can the var name include aws? Or can the aws key ID include the region, like other KMS providers?

2025-01-21 22:52 UTC, haydentherapper commented on cmd/certificate_maker/certificate_maker.go
> +	createCmd.Flags().StringVar(&kmsTenantID, "azure-tenant-id", "", "Azure KMS tenant ID")
same here and below, can the var names include the provider if these aren't meant to be generalized across KMS providers?

2025-01-21 22:52 UTC, haydentherapper commented on cmd/certificate_maker/certificate_maker.go
> +	createCmd.Flags().StringVar(&leafTemplatePath, "leaf-template", "pkg/certmaker/templates/leaf-template.json", "Path to leaf certificate template")
nit, can you group these flags by root/intermediate/leaf?

2025-01-21 22:52 UTC, haydentherapper commented on cmd/certificate_maker/certificate_maker.go
> +	createCmd.Flags().StringVar(&kmsVaultToken, "vault-token", "", "HashiVault token")
nit, can you move these up to the other KMS variables?

2025-01-21 22:52 UTC, haydentherapper commented on cmd/certificate_maker/certificate_maker.go
> +	}
do you need to validate the intermediate as well?

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/template.go
> +type CertificateTemplate struct {
Since the PR description mentioned smallstep, what was the motivation for creating your own template vs using smallstep's https://smallstep.com/docs/step-ca/templates/index.html?

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/templates/leaf-template.json
> +        "commonName": "https://fulcio.com"
Could we support templating (https://pkg.go.dev/text/template), or at least leave these values blank? I want to discourage copy-pasting of default values.

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/certmaker.go
> +	Region            string
If this is specific to AWS, can we include AWS in the name?

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/certmaker.go
> +	keyID := config.RootKeyID
i'd require rootkeyid be specified, this seems prone to accidental mistake

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/certmaker.go
> +	rootCert, err := x509util.CreateCertificate(rootTmpl, rootTmpl, rootPubKey, signerWrapper{sv})
Why not use `x509.CreateCertificate` from the standard library?

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/certmaker.go
> +type signerWrapper struct {
Is this needed? the KMS implementations implement Public and Sign - https://github.com/sigstore/sigstore/blob/main/pkg/signature/kms/gcp/signer.go#L144-L164

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/certmaker.go
> +	} else if cert.MaxPathLen == 0 {
I'd check that the SKID and AKID match to check that it's a root, as max path length = 0 could be set for a root as well.

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/templates/leaf-template.json
> +    "basicConstraints": {
Should we allow these values to be set in the template? Given that the certificates should conform to the cert profile, which is strict on basic constraints, key usage and extended key usage, can the template just be for subject, issuer, not before/after?

Then this is simplified to a single template for leaf/intermediate/root.

2025-01-21 22:52 UTC, haydentherapper commented on pkg/certmaker/template.go
> +	if tmpl.NotBefore == "" || tmpl.NotAfter == "" {
I'd slightly prefer an option to set the lifetime and use the current time rather than require exact timestamps.

2025-01-22 02:11 UTC, ianhundere commented on pkg/certmaker/template.go
> +type CertificateTemplate struct {
i'm actually using their template syntax w/ "go.step.sm/crypto/x509util" to parse those templates.

2025-01-22 02:12 UTC, ianhundere commented on pkg/certmaker/certmaker.go
> +	rootCert, err := x509util.CreateCertificate(rootTmpl, rootTmpl, rootPubKey, signerWrapper{sv})
this is so we can use stepca templates via "go.step.sm/crypto/x509util"

2025-01-22 02:56 UTC, ianhundere commented on pkg/certmaker/certmaker.go
> +type signerWrapper struct {
ah, good point / will remove and extend.

2025-01-22 05:49 UTC, ianhundere commented on pkg/certmaker/templates/leaf-template.json
> +    "basicConstraints": {
that makes a lot of sense, but as you mention below, provide an option to set the cert life (e.g. flag / env var).

2025-01-22 16:30 UTC, ianhundere commented
@haydentherapper 

i tackled most of your feedback except for:
- https://github.com/sigstore/fulcio/pull/1870#discussion_r1924461364
  - "an option to set the lifetime and use the current time rather than require exact timestamps."
  
  could i do this as a separate PR / feat ?
  
- https://github.com/sigstore/fulcio/pull/1870#discussion_r1924460629
  - using the template just for subject, issuer, and not before/after

  same as above, could we push this into another PR as a feat ?

- https://github.com/sigstore/fulcio/pull/1870#discussion_r1924449693
  - leave template fields like org, common blank or support templating (https://pkg.go.dev/text/template)

    and similar to the above, could i make these blank for now and then implement templating in the same PR as the suggestions above ?

2025-01-22 16:54 UTC, ianhundere commented on pkg/certmaker/templates/leaf-template.json
> +        "commonName": "https://fulcio.com"
i went ahead and made them blank for now / there's validation to ensure they're included, so the user will be prompted to fill them in if they forget to. 

maybe we could implement templating in another PR ?

2025-01-24 05:04 UTC, ianhundere commented on pkg/certmaker/templates/leaf-template.json
> +    "basicConstraints": {
okidoki, i include templating and a embed...so now templates are included w/ the binary as well as a positional arg for common name.

2025-01-24 05:05 UTC, ianhundere commented on pkg/certmaker/template.go
> +type CertificateTemplate struct {
i'm now using x509util's `TemplateData`.

2025-01-24 05:10 UTC, ianhundere commented
@haydentherapper okidoki, i implemented all your suggested feedback including templating.

the behavior now is that templates will be included via the embed package which are used as defaults / a user can still use  their own templates to take advantage of https://pkg.go.dev/go.step.sm/crypto/x509util for advanced use-cases.

2025-01-24 21:31 UTC, haydentherapper approved these changes
Thank you for the great work on this!

2025-01-24 21:36 UTC, merged

2025-01-24 21:37 UTC, ianhundere commented
> Thank you for the great work on this!

absolutely, the tsa PR is also up for review. have a good wknd!

2025-01-24 21:44 UTC, haydentherapper commented
@ianhundere Just realized one thing when reviewing the TSA PR. Should we remove the leaf certificate template processing from Fulcio? For the TSA, this is needed, as the leaf certificate signs timestamps. For Fulcio, Fulcio _is_ the CA so it issues leaf certificates.

2025-01-24 21:56 UTC, ianhundere commented
@haydentherapper ah, good point / so just to confirm, essentially remove all elements associated w/ leaf cert creation (e.g. leaf template, flags etc), correct ?

and should i do that in a separate PR ?

2025-01-24 21:58 UTC, haydentherapper commented
Sorry for two separate threads! I just replied on the TSA PR as well. I'd suggest that we make the leaf cert creation optional, and then point TSA operators to this repo, which will reduce code duplication. The only thing we need in the TSA repo then is the TSA templates for root/intermediate/leaf and a README.