bump sigstore/sigstore from 1.3.1 to 1.4.0
sigstore/fulcio pull request #745
Opened 2022-08-18 16:27 UTC by k4leung4

Signed-off-by: Kenny Leung <kleung@chainguard.dev>

#### Summary

bump sigstore/sigstore from 1.3.1 to 1.4.0

#### Release Note

NONE

#### Documentation

2022-08-18 16:29 UTC, haydentherapper approved these changes

2022-08-18 22:29 UTC, haydentherapper requested changes
Removing lgtm, seems like something changed?

2022-08-21 07:16 UTC, haydentherapper commented
To fix the test, update https://github.com/sigstore/fulcio/blob/main/pkg/server/grpc_server_test.go#L959 and https://github.com/sigstore/fulcio/blob/main/pkg/server/grpc_server_test.go#L1366 to be PublicKeyPEMType.

2022-08-21 13:21 UTC, k4leung4 commented
> To fix the test, update https://github.com/sigstore/fulcio/blob/main/pkg/server/grpc_server_test.go#L959 and https://github.com/sigstore/fulcio/blob/main/pkg/server/grpc_server_test.go#L1366 to be PublicKeyPEMType.

thanks for pointing me in the right direction. fixed.

2022-08-21 13:31 UTC, dlorenc approved these changes

2022-08-21 16:22 UTC, haydentherapper approved these changes

2022-08-21 16:23 UTC, merged